apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-node-latest
spec:
  params:
    - name: node-version
      type: string
      default: "v23"  # Specify the pre-release version to install
    - name: npm-version
      type: string
      default: ""  # Optional npm version
  workspaces:
    - name: output
      mountPath: /artifacts
  steps:
    - name: execute
      image: node:20  # Use a Node.js image for installation
      script: |
        #!/bin/bash

        NODE_VERSION="v23"
        echo "Node.js version to install: $NODE_VERSION"

        # Install NVM if not already installed
        if ! command -v nvm &> /dev/null; then
          echo "NVM not found. Installing NVM..."
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        fi

        # Install the specified Node.js version using the RC mirror
        echo "Attempting to install Node.js version $NODE_VERSION..."
        NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/rc nvm install "$NODE_VERSION" || {
          echo "RC installation failed. Attempting to install Node.js version $NODE_VERSION using Nightly mirror..."
          NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly nvm install "$NODE_VERSION"
        }

        # Create symlinks for Node.js and npm in the output workspace
        mkdir -p /artifacts/bin
        ln -s "$HOME/.nvm/versions/node/$NODE_VERSION/bin/node" /artifacts/bin/node
        ln -s "$HOME/.nvm/versions/node/$NODE_VERSION/bin/npm" /artifacts/bin/npm

        # Display the installed versions
        echo "Node.js version installed:"
        /artifacts/bin/node -v
        echo "NPM version installed:"
        /artifacts/bin/npm -v
