name: Slack Post
run-name: Posting the release into Slack
on:
  release:
    types: [published]
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Send success message to Slack release channel
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: C06JPF2LGQK
          payload: |
            {
              "text": ":mega: :package: Version 1 of the Node.js tracer (npm package @instana/collector and friends) has been released! :star-struck: :tada:",
              "attachments": [{
                "color": "good",
                "fields": [
                  {
                    "title": "Release Note",
                    "value": "<https://github.com/instana/nodejs/releases>"
                  },
                  {
                    "title": "Message",
                    "value": "Hey <@arya.mohanan@ibm.com>, please update the release notes. Thank you!"
                  }
                ]
              }]
            }
        env:
          SLACK_RELEASE_CHANNEL_ID: C06JPF2LGQK
